### PR TITLE
Throw exception on empty response when json is expected

### LINKED ISSUE #24: Warning thrown when response is null.
When doing `$report_api->queueReport($report_description);` it is possible that `HttpClient` returns `null` value as response. See https://github.com/Adobe-Marketing-Cloud/marketing-cloud-php-sdk/blob/master/lib/AdobeMarketingCloud/HttpClient.php#L218-L221
Note that exception is thrown when `json_decode` returns `null` and debug is enabled. In prod environment, debug is disabled, so value returned is `null`, despite docblock.
While that might be not a big deal by itself, this value is passed to [returnResponse](https://github.com/Adobe-Marketing-Cloud/marketing-cloud-php-sdk/blob/master/lib/AdobeMarketingCloud/Api/Report.php#L184) method on `Report` class, which expects value to be an array.

From my understanding, failure to [json]decode response would mean failed request and runtime exception has to be thrown, but looks like it will be BC break. 

Additionally to that, when calling `$report_api->Report($report_description);` it makes request to put report into a queue, server responds with invalid json, but library tries to fetch `$response['reportID']`, gets null (and throws notice), then uses this null-value to make another request to get report results, where finally gets valid response with error saying 'Report ID is required'

Ideas?

### PR DESCRIPTION
**Pull request by kkopachev**
Closes #24

### CODE REVIEW

File: lib/AdobeMarketingCloud/HttpClient.php [hunk 1]
```diff
@@ -215,9 +217,16 @@ protected function decodeResponse($response, $options = array())
         switch ($options['format'])
         {
             case 'json':
-                if ((null === $json = json_decode($response['response'], true)) && ($options['debug'] === true)) {
-                    throw new Exception("Response is not in JSON format: \n\n".print_r($response, true));
+                $json = json_decode($response['response'], TRUE);
+                if ($json === null) {
+                    $debug_printout = "";
```
Comment (stevja1) [inline lib/AdobeMarketingCloud/HttpClient.php]: One quick change -- could you change this to `debugPrintout`? Otherwise, it looks good. Thanks!

Comment (kkopachev) [reply lib/AdobeMarketingCloud/HttpClient.php]: done
